package mvc.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import mvc.beans.InspectorBean;

public class InspectorDAO {

    public static boolean registerInspector(InspectorBean inspector) {
        String loginQuery = "INSERT INTO login (login_username, login_password, login_role) VALUES (?, ?, 'inspector')";
        String inspectorQuery = "INSERT INTO inspector (login_id, inspector_name, phone) VALUES (?, ?, ?)";
        
        Connection conn = null;
        PreparedStatement pstmt1 = null;
        PreparedStatement pstmt2 = null;
        ResultSet rs = null;
        
        try {
            conn = DBConnection.getConnection();
            conn.setAutoCommit(false); // Start Transaction block

            // 1. Insert authentication account details into login table
            pstmt1 = conn.prepareStatement(loginQuery, Statement.RETURN_GENERATED_KEYS);
            pstmt1.setString(1, inspector.getUsername());
            pstmt1.setString(2, inspector.getPassword());
            pstmt1.executeUpdate();

            // Fetch the autogenerated login_id primary key index back
            rs = pstmt1.getGeneratedKeys();
            int generatedLoginId = 0;
            if (rs.next()) {
                generatedLoginId = rs.getInt(1);
            }

            // 2. Insert profile information into inspector table using the foreign key
            pstmt2 = conn.prepareStatement(inspectorQuery);
            pstmt2.setInt(1, generatedLoginId);
            pstmt2.setString(2, inspector.getInspectorName());
            pstmt2.setString(3, inspector.getPhone());
            pstmt2.executeUpdate();

            conn.commit(); // Save changes across both tables securely
            return true;
        } catch (SQLException e) {
            if (conn != null) {
                try { conn.rollback(); } catch (SQLException ex) { ex.printStackTrace(); }
            }
            e.printStackTrace();
            return false;
        } finally {
            try {
                if (rs != null) rs.close();
                if (pstmt1 != null) pstmt1.close();
                if (pstmt2 != null) pstmt2.close();
                if (conn != null) conn.close();
            } catch (SQLException e) { e.printStackTrace(); }
        }
    }

    public static List<InspectorBean> getAllInspectors() {
        List<InspectorBean> list = new ArrayList<>();
        String query = "SELECT * FROM inspector";
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(query);
             ResultSet rs = pstmt.executeQuery()) {
            while (rs.next()) {
                InspectorBean ins = new InspectorBean();
                ins.setInspectorId(rs.getInt("inspector_id"));
                ins.setLoginId(rs.getInt("login_id"));
                ins.setInspectorName(rs.getString("inspector_name"));
                ins.setPhone(rs.getString("phone"));
                list.add(ins);
            }
        } catch (SQLException e) { e.printStackTrace(); }
        return list;
    }
}